# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: starefossen/ruby-node:2-5

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:latest

cache:
  key: CM-Fulcrum
  untracked: true

variables:
  DISPLAY: :99.0
  PHANTOM_JS: phantomjs-2.1.1-linux-x86_64

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v
  - npm -v
  - script/gitlab-phantomjs-download
  - bundle install --without development production -j $(nproc) --path /cache
  - cp .env.sample .env
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake --trace fulcrum:setup db:setup

test:
  script:
    - bundle exec rspec
    - bundle exec rake --trace spec:javascripts
