language: ruby
cache: bundler
sudo: false
env:
  - "DB=postgresql"
before_script:
  - "cp .env.sample .env"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake --trace fulcrum:setup db:setup"
rvm:
  - 2.2.1
script:
  - "bundle exec rake travis"
